 SELECT Name FROM Employees WHERE
   DATE_FORMAT(DATE_ADD(DateOfBirth, INTERVAL YEAR(CURRENT_DATE)-YEAR(DateOfBirth) YEAR), '%m-%d')
   BETWEEN DATE_FORMAT(CURRENT_DATE, '%m-%d') AND DATE_FORMAT(DATE_ADD(CURRENT_DATE, INTERVAL 30 DAY), '%m-%d');
